#cloud-config

# Install required packages
package_update: true
packages:
  - apache2
  - mysql-server
  - php
  - php-mysql
  - libapache2-mod-php
  - php-cli

# Install Wordpress
runcmd:
  - wget https://wordpress.org/latest.tar.gz
  - tar -xzvf latest.tar.gz
  - sudo mv wordpress /var/www/html
  - sudo chown -R www-data:www-data /var/www/html/wordpress

# Configure database 
  - mysql -u root -e "CREATE DATABASE wordpress;"
  - mysql -u root -e "CREATE USER 'wordpressuser'@'localhost' IDENTIFIED BY 'password';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpressuser'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - sed -i "s/database_name_here/
